title: Aisleron
remote_theme: just-the-docs/just-the-docs

url: https://aisleron.com

aux_links:
  GitHub: https://github.com/thebatdan/Aisleron

favicon_ico: "/assets/images/favicon.ico"

# logo: "/assets/images/aisleron-32x32.png"

color_scheme: dark
