title: Aisleron
description: Streamline your shopping with this intuitive, easy-to-use shopping list app.
remote_theme: just-the-docs/just-the-docs

url: https://aisleron.com

aux_links:
  Template Repository: https://github.com/thebatdan/Aisleron

favicon_ico: "favicon.ico"

logo: "/assets/images/Aisleron-192x192.png"



