title: Aisleron
theme: just-the-docs

url: https://aisleron.com
repository: thebatdan/Aisleron # for github-metadata

permalink:

aux_links:
  GitHub: https://github.com/thebatdan/Aisleron


favicon_ico: "/assets/images/favicon.ico"

# logo: "/assets/images/aisleron-32x32.png"

# color_scheme: dark

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# External navigation links
nav_external_links:
  - title: Aisleron on GitHub
    url: https://github.com/thebatdan/Aisleron
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Aisleron Docs on GitHub
    url: https://github.com/aisleron/aisleron.docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

# exclude:
#  - README.md
