title: Aisleron
theme: just-the-docs
description: "Aisleron: Fly through the shops!"

url: https://aisleron.com
repository: aisleron/aisleron # for github-metadata

permalink:

aux_links:
  Google Play: https://play.google.com/store/apps/details?id=com.aisleron
  F-Droid: https://f-droid.org/en/packages/com.aisleron


favicon_ico: "/assets/images/favicon.ico"

# logo: "/assets/images/aisleron-32x32.png"

# color_scheme: dark

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# External navigation links
nav_external_links:
  - title: Aisleron on GitHub
    url: https://github.com/aisleron/aisleron
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Aisleron Docs on GitHub
    url: https://github.com/aisleron/aisleron.docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

exclude:
  - README.md

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-sitemap